/** German translations of PCF specification values (keys = English source text). */
export const pcfSpecValuesDe: Record<string, string> = {
  "0–1,000 ppbV benzene (6 scales from 0–5 ppbV)": "0–1.000 ppbV Benzol (6 Messbereiche ab 0–5 ppbV)",
  "0–10 Vdc / 4–20 mA": "0–10 Vdc / 4–20 mA",
  "0–10,000 mg/m³": "0–10.000 mg/m³",
  "0–10,000 mg/m³ (scalable)": "0–10.000 mg/m³ (skalierbar)",
  "0–10,000 ppmV TVOC": "0–10.000 ppmV TVOC",
  "0–10,000 ppmV TVOC; individual ranges per compound": "0–10.000 ppmV TVOC; individuelle Bereiche je Verbindung",
  "0–100 / 1,000 / 10,000 mg/m³": "0–100 / 1.000 / 10.000 mg/m³",
  "0–100 / 1,000 / 10,000 mg/m³ (other ranges available)": "0–100 / 1.000 / 10.000 mg/m³ (weitere Bereiche verfügbar)",
  "0–40 °C": "0–40 °C",
  "0–40 °C ambient": "0–40 °C Umgebung",
  "1 m": "1 m",
  "1 s from 0 to 90 % of f.s.d.": "1 s von 0 auf 90 % des Vollbereichs",
  "1,000 ml/min": "1.000 ml/min",
  "12 kg": "12 kg",
  "12–15 kg": "12–15 kg",
  "15 kg": "15 kg",
  "180 s basic cycle (modifiable on request)": "180 s Grundzyklus (auf Anfrage änderbar)",
  "180–200 °C": "180–200 °C",
  "180–200 °C (heated circuit)": "180–200 °C (beheizter Kreislauf)",
  "180–200 °C circuit": "Kreislauf 180–200 °C",
  "180–300 s (shorter on request)": "180–300 s (kürzer auf Anfrage)",
  "19″ rack mini GC": "Mini-GC im 19″ Rack",
  "19″ rack module": "19″-Rack-Modul",
  "19″ rack process analyser": "19″-Rack-Prozessanalysator",
  "2 gas cylinders": "2 Gasflaschen",
  "2 × 40 character lines": "2 × 40 Zeichen pro Zeile",
  "230 V 50 Hz (110 V 60 Hz optional)": "230 V 50 Hz (110 V 60 Hz optional)",
  "230 V 50 Hz (110 V optional)": "230 V 50 Hz (110 V optional)",
  "230/110 Vac, 50/60 Hz, max 300 VA": "230/110 Vac, 50/60 Hz, max. 300 VA",
  "2× 4.3″ touch-screen graphic displays": "2× 4,3″ grafische Touchscreen-Displays",
  "3 gas cylinders": "3 Gasflaschen",
  "3 m standard (optional longer)": "3 m Standard (optional länger)",
  "30 s standard (shorter on request)": "30 s Standard (kürzer auf Anfrage)",
  "390 × 290 × 230 mm (19″ rack module)": "390 × 290 × 230 mm (19″-Rack-Modul)",
  "3× 0–10 V / 4–20 mA (specific, TVOC, difference)": "3× 0–10 V / 4–20 mA (spezifisch, TVOC, Differenz)",
  "400 × 300 × 150 mm portable module": "400 × 300 × 150 mm tragbares Modul",
  "480 × 190 × 560 mm": "480 × 190 × 560 mm",
  "480 × 190 × 560 mm (19″ rack, W×H×D)": "480 × 190 × 560 mm (19″ Rack, B×H×T)",
  "483 × 185 × 450 mm (19″ rack)": "483 × 185 × 450 mm (19″ Rack)",
  "500 ml/min": "500 ml/min",
  "5–40 °C ambient": "5–40 °C Umgebung",
  "6 programmable scales, e.g. 0–5/10/50/100/500/1,000 ppmV (or mg/m³)": "6 programmierbare Messbereiche, z. B. 0–5/10/50/100/500/1.000 ppmV (oder mg/m³)",
  "6 scales from 0–5 ppmV VOC": "6 Bereiche ab 0–5 ppmV VOC",
  "640×200 px colour LCD touch screen with real-time analysis": "640×200 px Farb-LCD-Touchscreen mit Echtzeitanalyse",
  "< 0.05 µg/m³ benzene": "< 0,05 µg/m³ Benzol",
  "> 1 % of f.s.d.": "> 1 % des Vollbereichs",
  "Amplified signal proportional to concentration": "Verstärktes, der Konzentration proportionales Signal",
  "Analogue and serial interfaces": "Analoge und serielle Schnittstellen",
  "Analysis and calibration phase switching": "Umschaltung Analyse- und Kalibrierphase",
  "As per application (configured at order)": "Je nach Anwendung (bei Bestellung konfiguriert)",
  "Automatic GC cycle with thermal desorption": "Automatischer GC-Zyklus mit thermischer Desorption",
  "Benzene, toluene, ethylbenzene, xylenes (BTEX)": "Benzol, Toluol, Ethylbenzol, Xylole (BTEX)",
  "Bridge unbalance signal, amplified": "Brückenungleichgewichtssignal, verstärkt",
  "CH₄, CO₂ and light permanent gases": "CH₄, CO₂ und leichte permanente Gase",
  "CH₄, CO₂, H₂, O₂ and permanent gases": "CH₄, CO₂, H₂, O₂ und permanente Gase",
  "CH₄, TVOC, NMH and specific HC compounds": "CH₄, TVOC, NMH und spezifische KW-Verbindungen",
  "Calibrated capillary loop (0.6 cc)": "Kalibrierte Kapillarschleife (0,6 cc)",
  "Colour graphic display with touch screen": "Farbgrafikdisplay mit Touchscreen",
  "Compact subsystem with PCB": "Kompaktes Subsystem mit Leiterplatte",
  "Continuous and alternating analyser modes": "Kontinuierliche und alternierende Analysatormodi",
  "Continuous process gas chromatography": "Kontinuierliche Prozess-Gaschromatographie",
  "Discrete / non-continuous sampling": "Diskrete / nicht-kontinuierliche Probenahme",
  "Dual FID — simultaneous VOC and CH₄": "Dual-FID — gleichzeitige VOC- und CH₄-Messung",
  "Dynamic dilution / metrological calibrator": "Dynamische Verdünnung / metrologischer Kalibrator",
  "Electrical heating along PTFE/stainless path": "Elektrische Beheizung entlang PTFE/Edelstahl-Führung",
  "Emission stacks and industrial sources": "Emissionsquellen und industrielle Anlagen",
  "Engineered analogue signal proportional to concentration": "Aufbereitetes analoges Signal proportional zur Konzentration",
  "F.I.D. flame ionization detector at high temperature (180 °C)": "F.I.D.-Flammenionisationsdetektor bei hoher Temperatur (180 °C)",
  "FID air supply for PCF analysers": "FID-Luftversorgung für PCF-Analysatoren",
  "FID emission monitoring systems": "FID-Emissionsüberwachungssysteme",
  "FID for high temperatures (180 °C)": "FID für hohe Temperaturen (180 °C)",
  "FID or PID": "FID oder PID",
  "FID with GC column separation": "FID mit GC-Säulentrennung",
  "FID with GC separation": "FID mit GC-Trennung",
  "Field / laboratory gas organisation": "Feld- / Labor-Gasorganisation",
  "Field / portable monitoring kits": "Feld- / tragbare Monitoringsets",
  "Flame ionization detector (FID)": "Flammenionisationsdetektor (FID)",
  "From analyser or external controller": "Vom Analysator oder externen Regler",
  "Front-panel display with programming menu": "Frontpanel-Display mit Programmiermenü",
  "GC cycle for NMH determination (configurable)": "GC-Zyklus zur NMH-Bestimmung (konfigurierbar)",
  "Glass Duraglass": "Glas-Duraglass-Mischkammer",
  "Heated F.I.D. flame ionization detector (180 °C)": "Beheizter F.I.D.-Flammenionisationsdetektor (180 °C)",
  "Heated FID (180 °C)": "Beheizter FID (180 °C)",
  "Heated dust filter at probe head": "Beheizter Staubfilter an der Sonden-Spitze",
  "H₂ 28 cc/min; pure air 280 cc/min from internal generator": "H₂ 28 cc/min; Reine Luft 280 cc/min vom internen Generator",
  "H₂ 30 cc/min; pure air 300 cc/min": "H₂ 30 cc/min; Reine Luft 300 cc/min",
  "H₂ 30 ml/min; FID air 300 ml/min; service air 4.5 bar (local)": "H₂ 30 ml/min; FID-Luft 300 ml/min; Versorgungsluft 4,5 bar (lokal)",
  "H₂, FID air, nitrogen/service air as per configuration": "H₂, FID-Luft, Stickstoff/Versorgungsluft je nach Konfiguration",
  "Linearity, LDL, repeatability at multiple steps": "Linearität, LDL, Wiederholbarkeit in mehreren Stufen",
  "Low — responds to organic carbon broadly": "Gering — breite Ansprechbarkeit auf organischen Kohlenstoff",
  "Lower than FID; excellent stability": "Geringer als FID; ausgezeichnete Stabilität",
  "Medium — ppm fractions": "Mittel — ppm-Bereich",
  "Multi-line / multi-point stream selector": "Mehrleitungs- / Mehrpunkt-Strömungswahlschalter",
  "Multiple lengths on request": "Verschiedene Längen auf Anfrage",
  "Occasional methane fraction verification": "Gelegentliche Überprüfung der Methanfraktion",
  "On-board graphic display": "Integriertes Grafikdisplay",
  "Photo ionization detector (PID)": "Photoionisationsdetektor (PID)",
  "Portable 19″ module with carrying case": "Tragbares 19″-Modul mit Transportkoffer",
  "Portable analyser": "Tragbarer Analysator",
  "Pure air and hydrogen at controlled flow": "Reine Luft und Wasserstoff bei geregelter Strömung",
  "RS-232": "RS-232",
  "RS-232 (9-pin)": "RS-232 (9-polig)",
  "RS-232; analogue 0–10 V / 4–20 mA": "RS-232; analog 0–10 V / 4–20 mA",
  "Rack or bench module": "Rack- oder Tischmodul",
  "Seconds to 90 % of f.s.d.": "Sekunden bis 90 % des Vollbereichs",
  "Serial / analogue per system configuration": "Seriell / analog je Systemkonfiguration",
  "Stack gases up to ~100 °C": "Abgase bis ~100 °C",
  "Stainless steel": "Edelstahl",
  "Stainless steel (S.S.)": "Edelstahl (S.S.)",
  "Standard and ex-proof": "Standard- und Ex-Schutz-Ausführung",
  "TCD (thermal conductivity / Wheatstone bridge)": "TCD (Wärmeleitfähigkeitsdetektor / Wheatstone-Brücke)",
  "TVOC, CH₄, NMH and specific reactive HC": "TVOC, CH₄, NMH und spezifische reaktive KW",
  "Thermal conductivity detector (TCD)": "Wärmeleitfähigkeitsdetektor (TCD)",
  "Two-injection GC cycle": "GC-Zyklus mit zwei Injektionen",
  "Typically 3 m (options available)": "Üblicherweise 3 m (weitere Varianten)",
  "UNI EN 10263 / EN 12619 sampling practice": "Probenahmepraxis nach UNI EN 10263 / EN 12619",
  "UNI EN 12619:2013": "UNI EN 12619:2013",
  "Up to 4 mass flow controllers": "Bis zu 4 Massendurchflussregler (MFC)",
  "VOC, aromatics, unsaturated HC": "VOC, Aromaten, ungesättigte KW",
  "Zero / ultra-pure air generation (UPP)": "Erzeugung von Null- / ultrareiner Luft (UPP)",
  "~300 ml/min class (per analyser demand)": "Ca. 300 ml/min (je nach Analysatorbedarf)",
  "±0.1 µg/m³ benzene": "±0,1 µg/m³ Benzol",
  "±0.4 % of f.s.d.": "±0,4 % des Vollbereichs",
  "±1 % of f.s.d.": "±1 % des Vollbereichs",
  "±15 Vdc": "±15 Vdc"
};
